import { useRef, Suspense, useMemo } from 'react'
import * as THREE from 'three'
import { Canvas, useFrame } from '@react-three/fiber'
import { useGLTF, Stage, Grid, OrbitControls, Environment } from '@react-three/drei'
import { EffectComposer, Bloom, ToneMapping } from '@react-three/postprocessing'
import { easing } from 'maath'
import { useControls } from 'leva'
import Grass from './Grass'

export default function App() {
  const { autoRotate, rotateSpeed } = useControls('Camera', {
    autoRotate:  { value: true },
    rotateSpeed: { value: 0.05, min: -2, max: 2, step: 0.01, label: 'Rotate Speed' },
  })

  const { bladeHeight, bladeWidth, density, fieldRadius, windSpeed, tipHex, bottomHex } = useControls('Grass', {
    bladeHeight: { value: 0.28,   min: 0.05, max: 1.5,    step: 0.01,    label: 'Blade Height' },
    bladeWidth:  { value: 0.05,   min: 0.01, max: 0.2,    step: 0.005,   label: 'Blade Width'  },
    density:     { value: 150,    min: 10,    max: 300,     step: 5,       label: 'Density (k)'  },
    fieldRadius: { value: 50,     min: 5,    max: 100,     step: 1,       label: 'Radius'       },
    windSpeed:   { value: 1.0,    min: 0,    max: 5,       step: 0.1,     label: 'Wind Speed'   },
    tipHex:      { value: '#009900', label: 'Tip Color'  },
    bottomHex:   { value: '#001a00', label: 'Root Color' },
  })

  // THREE.js r160 ColorManagement is enabled by default: new THREE.Color('#hex') already
  // auto-converts sRGB→linear internally. Calling convertSRGBToLinear() again would apply
  // the gamma curve twice and produce colours ~4× too dark. Just use the Color directly.
  const tipColor    = useMemo(() => new THREE.Color(tipHex),    [tipHex])
  const bottomColor = useMemo(() => new THREE.Color(bottomHex), [bottomHex])

  return (
    <Canvas flat shadows camera={{ position: [-15, 0, 10], fov: 25 }}>
      <fog attach="fog" args={['black', 15, 22.5]} />
      <Stage intensity={0.5} environment="city" shadows={{ type: 'accumulative', bias: -0.001, intensity: Math.PI }} adjustCamera={false}>
        <Kamdo rotation={[0, Math.PI, 0]} />
      </Stage>
      <Grid renderOrder={-1} position={[0, -1.85, 0]} infiniteGrid cellSize={0.6} cellThickness={0.6} sectionSize={3.3} sectionThickness={1.5} sectionColor={[0.5, 0.5, 10]} fadeDistance={30} />
      <Suspense fallback={null}>
        <Grass
          options={{ bW: bladeWidth, bH: bladeHeight, joints: 5 }}
          instances={density * 1000}
          radius={fieldRadius}
          windSpeed={windSpeed}
          tipColor={tipColor}
          bottomColor={bottomColor}
        />
      </Suspense>
      {/* Soft polar limits: can look from nearly overhead (π/6) to just below horizon (π/1.9).
          Prevents flipping under the ground while still giving full orbit freedom. */}
      <OrbitControls
        autoRotate={autoRotate}
        autoRotateSpeed={rotateSpeed}
        makeDefault
        minPolarAngle={Math.PI / 6}
        maxPolarAngle={Math.PI / 1.9}
      />
      <EffectComposer disableNormalPass>
        <Bloom luminanceThreshold={2} mipmapBlur />
        <ToneMapping />
      </EffectComposer>
      <Environment background preset="sunset" blur={0.8} />
    </Canvas>
  )
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.0 s2wt_kamdo_industrial_divinities.glb --transform --simplify
Author: Hansalex (https://sketchfab.com/Hansalex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/s2wt-kamdo-industrial-divinities-f503b70ac05e49a38c81100d71599a1b
Title: S2WT "Kamdo" (Industrial Divinities)
*/

function Kamdo(props) {
  const head = useRef()
  const stripe = useRef()
  const light = useRef()
  const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL}/s2wt_kamdo_industrial_divinities-transformed.glb`)
  useFrame((state, delta) => {
    const t = (1 + Math.sin(state.clock.elapsedTime * 2)) / 2
    stripe.current.color.setRGB(2 + t * 20, 2, 20 + t * 50)
    easing.dampE(head.current.rotation, [0, state.pointer.x * (state.camera.position.z > 1 ? 1 : -1), 0], 0.4, delta)
    light.current.intensity = 1 + t * 4
  })
  return (
    <group {...props}>
      <mesh castShadow receiveShadow geometry={nodes.body001.geometry} material={materials.Body} />
      <group ref={head}>
        <mesh castShadow receiveShadow geometry={nodes.head001.geometry} material={materials.Head} />
        <mesh castShadow receiveShadow geometry={nodes.stripe001.geometry}>
          <meshBasicMaterial ref={stripe} toneMapped={false} />
          <pointLight ref={light} intensity={1} color={[10, 2, 5]} distance={2.5} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload(`${process.env.PUBLIC_URL}/s2wt_kamdo_industrial_divinities-transformed.glb`)
