// @ts-nocheck
import { useRef, Suspense, useMemo } from 'react'
import * as THREE from 'three'
import { useFrame, useLoader } from '@react-three/fiber'
import { useGLTF, Stage, Grid, OrbitControls, Environment } from '@react-three/drei'
import { EffectComposer, Bloom, ToneMapping } from '@react-three/postprocessing'
import { easing } from 'maath'
import { useControls } from 'leva'
import bladeDiffuse from './resources/blade_diffuse.jpg'
import bladeAlpha from './resources/blade_alpha.jpg'
import './GrassMaterial'

// ─── Scene (exported for Triplex — no Canvas wrapper) ────────────────────────
export function Scene() {
  const { autoRotate, rotateSpeed } = useControls('Camera', {
    autoRotate:  { value: true },
    rotateSpeed: { value: 0.05, min: -2, max: 2, step: 0.01, label: 'Rotate Speed' },
  })

  const { bladeHeight, bladeWidth, density, fieldRadius, windSpeed, tipHex, bottomHex } = useControls('Grass', {
    bladeHeight: { value: 0.28,      min: 0.05, max: 1.5,  step: 0.01,  label: 'Blade Height' },
    bladeWidth:  { value: 0.05,      min: 0.01, max: 0.2,  step: 0.005, label: 'Blade Width'  },
    density:     { value: 150,       min: 10,   max: 300,  step: 5,     label: 'Density (k)'  },
    fieldRadius: { value: 50,        min: 5,    max: 100,  step: 1,     label: 'Radius'       },
    windSpeed:   { value: 1.0,       min: 0,    max: 5,    step: 0.1,   label: 'Wind Speed'   },
    tipHex:      { value: '#009900', label: 'Tip Color'  },
    bottomHex:   { value: '#001a00', label: 'Root Color' },
  })

  const tipColor    = useMemo(() => new THREE.Color(tipHex),    [tipHex])
  const bottomColor = useMemo(() => new THREE.Color(bottomHex), [bottomHex])

  return (
    <>
      <fog attach="fog" args={['black', 15, 22.5]} />
      <Stage intensity={0.5} environment="city" shadows={{ type: 'accumulative', bias: -0.001, intensity: Math.PI }} adjustCamera={false}>
        <Kamdo rotation={[0, Math.PI, 0]} />
      </Stage>
      <Grid renderOrder={-1} position={[0, -1.85, 0]} infiniteGrid cellSize={0.6} cellThickness={0.6} sectionSize={3.3} sectionThickness={1.5} sectionColor={new THREE.Color().setRGB(0.5, 0.5, 10)} fadeDistance={30} />
      <Suspense fallback={null}>
        <Grass
          options={{ bW: bladeWidth, bH: bladeHeight, joints: 5 }}
          instances={density * 1000}
          radius={fieldRadius}
          windSpeed={windSpeed}
          tipColor={tipColor}
          bottomColor={bottomColor}
        />
      </Suspense>
      <OrbitControls
        autoRotate={autoRotate}
        autoRotateSpeed={rotateSpeed}
        makeDefault
        minPolarAngle={Math.PI / 6}
        maxPolarAngle={Math.PI / 1.9}
      />
      <EffectComposer disableNormalPass>
        <Bloom luminanceThreshold={2} mipmapBlur />
        <ToneMapping />
      </EffectComposer>
      <Environment background preset="sunset" blur={0.8} />
    </>
  )
}

// ─── Kamdo model ─────────────────────────────────────────────────────────────
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.0 s2wt_kamdo_industrial_divinities.glb --transform --simplify
Author: Hansalex (https://sketchfab.com/Hansalex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/s2wt-kamdo-industrial-divinities-f503b70ac05e49a38c81100d71599a1b
Title: S2WT "Kamdo" (Industrial Divinities)
*/
function Kamdo(props: JSX.IntrinsicElements['group']) {
  const head   = useRef<THREE.Group>(null!)
  const stripe = useRef<THREE.MeshBasicMaterial>(null!)
  const light  = useRef<THREE.PointLight>(null!)
  const { nodes, materials } = useGLTF('/s2wt_kamdo_industrial_divinities-transformed.glb') as any
  useFrame((state, delta) => {
    const t = (1 + Math.sin(state.clock.elapsedTime * 2)) / 2
    stripe.current.color.setRGB(2 + t * 20, 2, 20 + t * 50)
    easing.dampE(head.current.rotation, [0, state.pointer.x * (state.camera.position.z > 1 ? 1 : -1), 0], 0.4, delta)
    light.current.intensity = 1 + t * 4
  })
  return (
    <group {...props}>
      <mesh castShadow receiveShadow geometry={nodes.body001.geometry} material={materials.Body} />
      <group ref={head}>
        <mesh castShadow receiveShadow geometry={nodes.head001.geometry} material={materials.Head} />
        <mesh castShadow receiveShadow geometry={nodes.stripe001.geometry}>
          <meshBasicMaterial ref={stripe} toneMapped={false} />
          <pointLight ref={light} intensity={1} color={[10, 2, 5]} distance={2.5} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/s2wt_kamdo_industrial_divinities-transformed.glb')

// ─── Grass field ─────────────────────────────────────────────────────────────
interface GrassProps {
  options?: { bW: number; bH: number; joints: number }
  radius?: number
  instances?: number
  groundY?: number
  windSpeed?: number
  tipColor?: THREE.Color
  bottomColor?: THREE.Color
  [key: string]: any
}

function useIsMobile() {
  return /Mobi|Android|iPhone|iPad|iPod/i.test(navigator.userAgent)
}

function Grass({
  options = { bW: 0.05, bH: 0.28, joints: 5 },
  radius = 50,
  instances = 150000,
  groundY = -1.85,
  windSpeed = 1.0,
  tipColor,
  bottomColor,
  ...props
}: GrassProps) {
  const { bW, bH, joints } = options
  const materialRef = useRef<any>()
  const isMobile = useIsMobile()
  const effectiveInstances = isMobile ? Math.min(instances, 10000) : instances
  const [texture, alphaMap] = useLoader(THREE.TextureLoader, [bladeDiffuse, bladeAlpha])
  const attributeData = useMemo(
    () => getAttributeData(effectiveInstances, radius),
    [effectiveInstances, radius]
  )
  const baseGeom = useMemo(
    () => new THREE.PlaneGeometry(bW, bH, 1, joints).translate(0, bH / 2, 0),
    [bW, bH, joints]
  )

  useFrame((state) => {
    materialRef.current.uniforms.time.value = (state.clock.elapsedTime / 4) * windSpeed
  })

  const groundGeo = useMemo(() => new THREE.PlaneGeometry(200, 200).rotateX(-Math.PI / 2), [])

  return (
    <group position={[0, groundY, 0]} {...props}>
      <mesh geometry={groundGeo} position={[0, -0.01, 0]}>
        <meshStandardMaterial color="#000f00" />
      </mesh>
      <mesh frustumCulled={false}>
        <instancedBufferGeometry
          key={`${bW}-${bH}-${joints}`}
          instanceCount={effectiveInstances}
          index={baseGeom.index}
          attributes-position={baseGeom.attributes.position}
          attributes-uv={baseGeom.attributes.uv}
        >
          <instancedBufferAttribute attach="attributes-offset"           args={[new Float32Array(attributeData.offsets), 3]} />
          <instancedBufferAttribute attach="attributes-orientation"      args={[new Float32Array(attributeData.orientations), 4]} />
          <instancedBufferAttribute attach="attributes-stretch"          args={[new Float32Array(attributeData.stretches), 1]} />
          <instancedBufferAttribute attach="attributes-halfRootAngleSin" args={[new Float32Array(attributeData.halfRootAngleSin), 1]} />
          <instancedBufferAttribute attach="attributes-halfRootAngleCos" args={[new Float32Array(attributeData.halfRootAngleCos), 1]} />
        </instancedBufferGeometry>
        <grassMaterial
          ref={materialRef}
          map={texture}
          alphaMap={alphaMap}
          toneMapped={false}
          bladeHeight={bH}
          {...(tipColor    !== undefined && { tipColor    })}
          {...(bottomColor !== undefined && { bottomColor })}
        />
      </mesh>
    </group>
  )
}

function getAttributeData(instances: number, radius: number) {
  const offsets: number[]         = []
  const orientations: number[]    = []
  const stretches: number[]       = []
  const halfRootAngleSin: number[] = []
  const halfRootAngleCos: number[] = []

  let quaternion_0 = new THREE.Vector4()
  let quaternion_1 = new THREE.Vector4()

  const tiltMin = -0.25
  const tiltMax =  0.25

  for (let i = 0; i < instances; i++) {
    const theta   = Math.random() * Math.PI * 2
    const r       = Math.sqrt(Math.random()) * radius
    offsets.push(Math.cos(theta) * r, 0, Math.sin(theta) * r)

    let angle = Math.PI - Math.random() * (2 * Math.PI)
    halfRootAngleSin.push(Math.sin(0.5 * angle))
    halfRootAngleCos.push(Math.cos(0.5 * angle))

    let axis = new THREE.Vector3(0, 1, 0)
    quaternion_0.set(axis.x * Math.sin(angle / 2), axis.y * Math.sin(angle / 2), axis.z * Math.sin(angle / 2), Math.cos(angle / 2)).normalize()

    angle = Math.random() * (tiltMax - tiltMin) + tiltMin
    axis  = new THREE.Vector3(1, 0, 0)
    quaternion_1.set(axis.x * Math.sin(angle / 2), axis.y * Math.sin(angle / 2), axis.z * Math.sin(angle / 2), Math.cos(angle / 2)).normalize()
    quaternion_0 = multiplyQuaternions(quaternion_0, quaternion_1)

    angle = Math.random() * (tiltMax - tiltMin) + tiltMin
    axis  = new THREE.Vector3(0, 0, 1)
    quaternion_1.set(axis.x * Math.sin(angle / 2), axis.y * Math.sin(angle / 2), axis.z * Math.sin(angle / 2), Math.cos(angle / 2)).normalize()
    quaternion_0 = multiplyQuaternions(quaternion_0, quaternion_1)

    orientations.push(quaternion_0.x, quaternion_0.y, quaternion_0.z, quaternion_0.w)
    stretches.push(i < instances / 3 ? Math.random() * 0.6 : Math.random() * 0.3)
  }

  return { offsets, orientations, stretches, halfRootAngleCos, halfRootAngleSin }
}

function multiplyQuaternions(q1: THREE.Vector4, q2: THREE.Vector4): THREE.Vector4 {
  return new THREE.Vector4(
     q1.x * q2.w + q1.y * q2.z - q1.z * q2.y + q1.w * q2.x,
    -q1.x * q2.z + q1.y * q2.w + q1.z * q2.x + q1.w * q2.y,
     q1.x * q2.y - q1.y * q2.x + q1.z * q2.w + q1.w * q2.z,
    -q1.x * q2.x - q1.y * q2.y - q1.z * q2.z + q1.w * q2.w,
  )
}
